### ISSUE TITLE
plugin [decompound] is incompatible with version [5.4.0]; was designed for version [5.1.1]

### ISSUE THREAD

**Issue by expero** [jprante/elasticsearch-analysis-decompound#48]
-> Downloading http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/5.4.0.0/elasticsearch-analysis-decompound-5.4.0.0-plugin.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [decompound] is incompatible with version [5.4.0]; was designed for version [5.1.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:428)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:495)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:199)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

Running on:
[2017-05-15T11:02:40,575][INFO ][o.e.n.Node               ] version[5.4.0], pid[9016], build[780f8c4/2017-04-28T17:43:27.229Z], OS[Mac OS X/10.12.4/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_25/25.25-b02]

**Comment by expero** [comment]
[This](https://github.com/jprante/elasticsearch-analysis-decompound/issues/40#issuecomment-277554968) helps:
https://github.com/jprante/elasticsearch-analysis-decompound/issues/40#issuecomment-277554968

**Comment by jprante** [comment]
Thanks. There was a small plugin build glitch. I have uploaded the plugin zip again with correct version in the descriptor.

**Comment by expero** [comment]
Thanks for the fix.
